@startuml

title MODELE RECLAMATION CLIENT \n

namespace com.talents.reclamation.rec_model {
    class com.talents.reclamation.rec_model.Claim {
        - id: Integer
        - claimType: String
        - immediateTreatment: Integer
        - object: String
        - origin: Integer
        - receptionDate: Date
        - priority: String
        - description: String
    }

    class com.talents.reclamation.rec_model.Client {
        - id: Integer
        - clientCode: Integer
        - lastname: String
        - firstname: String
        - address: String
        - email: String
        - clientType: String
        - sensitiveClient: Boolean
    }

    class com.talents.reclamation.rec_model.Ticket {
        - id: Integer
        - ticketType: String
        - project: String
    }

}



com.talents.reclamation.rec_model.Claim .up.|> java.io.Serializable
com.talents.reclamation.rec_model.Client .up.|> java.io.Serializable
com.talents.reclamation.rec_model.Ticket .up.|> java.io.Serializable
com.talents.reclamation.rec_model.Ticket "1" --> "*" com.talents.reclamation.rec_model.Claim : contains
com.talents.reclamation.rec_model.Ticket "1" <-- "*" com.talents.reclamation.rec_model.Client : create


@enduml